const lang = {
  en: {
    search: "Search",
    placeHolder: "Search for movies, TV shows, and more...",
    home: "Home",
    myProfile: "My Profile",
    signOut: "Sign Out",
    watchlist: "My Watchlist",
    gptSearch: "GPT Search",
    play: "Play",
    moreInfo: "More Info",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcoming: "Upcoming",
    addedToWatchlist: "Added to Watchlist",
    addToWatchlist: "Add to Watchlist",
    trailerUnavailable: "Trailer Unavailable",
    manageProfiles: "Manage Profiles",
    moviesInWatchlist: "Movies in your Watchlist",
    askAssistant: "Ask for a movie...",
    send: "Send",
    clear: "Clear",
    whatToWatch: "What do you want to watch?",
    describeVibe: "Describe a vibe, genre, or movie — AI finds it",
    all: "All",
    editProfile: "Edit Profile",
    save: "Save",
    cancel: "Cancel",
    selectAvatar: "Select an Avatar",
    avatar: "Avatar",
    displayName: "Display Name",
    backToBrowse: "Back to Browse",
    whoIsWatching: "Who's watching?",
    genres: {
      Action: "Action",
      Comedy: "Comedy",
      Horror: "Horror",
      Drama: "Drama",
      Romance: "Romance",
      Thriller: "Thriller",
      Animation: "Animation",
      Documentary: "Documentary",
      Adventure: "Adventure",
      Crime: "Crime",
      Family: "Family",
      Fantasy: "Fantasy",
      History: "History",
      Music: "Music",
      Mystery: "Mystery",
      "Science Fiction": "Sci-Fi",
      "TV Movie": "TV Movie",
      War: "War",
      Western: "Western",
    }
  },
  hindi: {
    search: "खोजें",
    placeHolder: "फिल्में, टीवी शो और बहुत कुछ खोजें...",
    home: "होम",
    myProfile: "मेरी प्रोफ़ाइल",
    signOut: "साइन आउट",
    watchlist: "मेरी वॉचलिस्ट",
    gptSearch: "जीपीटी खोज",
    play: "चलाएं",
    moreInfo: "अधिक जानकारी",
    nowPlaying: "अब चल रहे हैं",
    popular: "लोकप्रिय",
    topRated: "शीर्ष रेटेड",
    upcoming: "आने वाले",
    addedToWatchlist: "वॉचलिस्ट में जोड़ा गया",
    addToWatchlist: "वॉचलिस्ट में जोड़ें",
    trailerUnavailable: "ट्रेलर अनुपलब्ध",
    manageProfiles: "प्रोफ़ाइल प्रबंधित करें",
    moviesInWatchlist: "आपकी वॉचलिस्ट में फिल्में",
    askAssistant: "मूवी के लिए पूछें...",
    send: "भेजें",
    clear: "साफ़ करें",
    whatToWatch: "आप क्या देखना चाहते हैं?",
    describeVibe: "वाइब, शैली, या फिल्म का वर्णन करें — AI इसे ढूंढ लेगा",
    all: "सभी",
    editProfile: "प्रोफ़ाइल संपादित करें",
    save: "सहेंजे",
    cancel: "रद्द करें",
    selectAvatar: "अवतार चुनें",
    avatar: "अवतार",
    displayName: "प्रदर्शित नाम",
    backToBrowse: "ब्राउज़ पर वापस जाएं",
    whoIsWatching: "कौन देख रहा है?",
    genres: {
      Action: "एक्शन",
      Comedy: "कॉमेडी",
      Horror: "डरावनी",
      Drama: "नाटक",
      Romance: "रोमांस",
      Thriller: "थ्रिलर",
      Animation: "एनीमेशन",
      Documentary: "वृत्तचित्र",
      Adventure: "साहसिक",
      Crime: "अपराध",
      Family: "परिवार",
      Fantasy: "फंतासी",
      History: "इतिहास",
      Music: "संगीत",
      Mystery: "रहस्य",
      "Science Fiction": "विज्ञान कथा",
      "TV Movie": "टीवी मूवी",
      War: "युद्ध",
      Western: "पश्चिमी",
    }
  },
  spanish: {
    search: "Buscar",
    placeHolder: "Buscar películas, programas de TV y más...",
    home: "Inicio",
    myProfile: "Mi Perfil",
    signOut: "Cerrar Sesión",
    watchlist: "Mi Lista",
    gptSearch: "Búsqueda GPT",
    play: "Reproducir",
    moreInfo: "Más Info",
    nowPlaying: "En Cartelera",
    popular: "Populares",
    topRated: "Mejor Valoradas",
    upcoming: "Próximamente",
    addedToWatchlist: "Añadido a Mi Lista",
    addToWatchlist: "Añadir a Mi Lista",
    trailerUnavailable: "Tráiler no disponible",
    manageProfiles: "Administrar Perfiles",
    moviesInWatchlist: "Películas en tu Lista",
    askAssistant: "Pide una película...",
    send: "Enviar",
    clear: "Limpiar",
    whatToWatch: "¿Qué quieres ver?",
    describeVibe: "Describe una vibra o género — la IA lo encuentra",
    all: "Todo",
    editProfile: "Editar Perfil",
    save: "Guardar",
    cancel: "Cancelar",
    selectAvatar: "Selecciona un Avatar",
    avatar: "Avatar",
    displayName: "Nombre para mostrar",
    backToBrowse: "Volver a Inicio",
    whoIsWatching: "¿Quién está viendo?",
    genres: {
      Action: "Acción",
      Comedy: "Comedia",
      Horror: "Terror",
      Drama: "Drama",
      Romance: "Romance",
      Thriller: "Suspense",
      Animation: "Animación",
      Documentary: "Documental",
      Adventure: "Aventura",
      Crime: "Crimen",
      Family: "Familia",
      Fantasy: "Fantasía",
      History: "Historia",
      Music: "Música",
      Mystery: "Misterio",
      "Science Fiction": "Ciencia Ficción",
      "TV Movie": "Película de TV",
      War: "Guerra",
      Western: "Occidental",
    }
  },
};

export default lang;
